# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9883f9fe419d8e61bc0b3d92bd3cf0ce4241ea23b0b16a55abbccac9b374c03f011ed7923e87bf46e8ac185620088267b4fa9ac59c07e28a9509749c8b0b2558

test:
  secret_key_base: 543a89ec6bf49c501c01ff2f0cdb2b4036eaf23357e27259cd7f6d1f9dd717eba20c0e0a7d41786335a227d5a3cf952b0cd957e19ed3b244f5be12d579261bf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
